function [ R ] = toRot( phi, theta, psi )
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here

R = [cos(psi)*cos(theta) - sin(phi)*sin(psi)*sin(theta),...
    -cos(phi)*sin(psi),...
    cos(phi)*sin(theta) + cos(theta)*sin(phi)*sin(psi);
    cos(theta)*sin(psi) + cos(psi)*sin(phi)*sin(theta),...
    cos(phi)*cos(psi),...
    sin(psi)*sin(theta) - cos(psi)*cos(theta)*sin(phi);
    -cos(phi)*sin(theta),...
    sin(phi),...
    cos(phi)*cos(theta)];



end

